# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 04:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ripam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
