# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ripam', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='plaid_category_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
