# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ripam', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='transactions_last_synced',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
